### PR TITLE
random treasure and change drawtext

### PR DESCRIPTION
**Pull request by B4NGDAI**

### CODE REVIEW

**Comment by RexShack** [comment]
get these errors
Screenshot 2023-08-14 150002

**Comment by TehGuardian** [comment]
Hes using ox_lib? probably shouldn't add this if your not going to add ox_lib.

**Comment by B4NGDAI** [comment]
fixed^^

**Comment by RexShack** [comment]
still seeing errors, see what you are trying to do will have a go

**Pull request closed without merging**
